### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Ayush62** [nextcloud/weather#100] opened 2022-02-16 13:54 UTC
Whenever i try to add the weather i get a fatal error.
I already re-generated a new key on openweathermap and i restarted the cloud, but i still have the same error. 
Does someone know what to do?

![Screenshot 2022-02-16 145439](https://user-images.githubusercontent.com/43236774/154278935-1a726e7f-e99f-420e-ad36-b017815eb26c.png)

**Comment by elgorro** [comment] 2022-02-16 22:54
Duplicate of #86 and openweathermap has updated their api.

**Comment by mesohorne** [comment] 2022-03-10 18:09
getting the same issue on fresh install. Log is empty, api key is updated

**Comment by e-alfred** [comment] 2022-12-25 20:23
Should be fixed by https://github.com/nextcloud/weather/pull/103.

**Closed by e-alfred** 2022-12-25 20:23 UTC
