### ISSUE TITLE
How to display weather temp in *F not *C 27.0.0?

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [nextcloud/weather#112] opened 2023-06-22 02:42 UTC
I don't know what all of  this is needed but here's what I know. In short I'm trying to find out how to make the Weather tile on the dashboard of NC display my temp in *F instead of *C, I have my language and Location set to "English (US/United States)" already.

 **Weather app bundles with install is only showing data in *C on dashboard, I'd like *F since I'm in the US. Any other readings I've yet to discover, but would like them in Imperial too.**

### Steps to reproduce
1. **install Nextcloud Docker on Unraid**
2. **Look at weather tile on Dashboard**
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: **Unraid **

**Web server:**

**Database:** **MariaDB**

**PHP version:** **? 8.2.something**

**Nextcloud version:** (see Nextcloud admin page) **27.0.0**

**Updated from an older Nextcloud/ownCloud or fresh install:** **updates, Been in *C since installed not long ago with 24.x.x**

**Where did you install Nextcloud from:** **Unraid Community Application Tab (Linuxserver/Ibracorp repo)**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by joshtrichards** [comment] 2023-12-24 14:32
Duplicate of nextcloud/server#23486

That functionality is provided by the `weather_status` dashboard widget app (not this app).

**Closed by joshtrichards** 2023-12-24 14:32 UTC
